[supervisord]
nodaemon=true
user=root

[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf --daemonize no
autostart=true
autorestart=true

[program:memcached]
command=/usr/bin/memcached -u memcache -c 1024 -m 64 -l 0.0.0.0
autostart=true
autorestart=true

[program:webapp]
command=node server.js
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:seed_redis]
command=/bin/bash -c "sleep 3 && redis-cli set admin_session_token 'FLAG-{MASSCAN_IS_BLAZING_FAST_AND_FOUND_MY_CACHE}' && redis-cli set auth_bypass 'false'"
autostart=true
autorestart=false
